// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

#define PIN_On_board_MAP MM100_IN_MAP2_ANALOG
#define PIN_101 MM100_INJ1
#define PIN_102 MM100_INJ2
#define PIN_103 MM100_INJ3
#define PIN_104 MM100_INJ5
#define PIN_105 MM100_INJ4
#define PIN_106 MM100_INJ6
#define PIN_2 MM100_INJ8
#define PIN_5 MM100_IGN1
#define PIN_6 MM100_IGN7
#define PIN_8_switch_inputs E12
#define PIN_8_event_inputs E12
#define PIN_10_switch_inputs B1
#define PIN_10_event_inputs B1
#define PIN_17_switch_inputs E13
#define PIN_17_event_inputs E13
#define PIN_20 MM100_OUT_PWM2
#define PIN_23 MM100_IN_CLT_ANALOG
#define PIN_29_switch_inputs E14
#define PIN_29_event_inputs E14
#define PIN_31 MM100_IN_O2S2_ANALOG
#define PIN_34 MM100_IN_VBATT
#define PIN_J1_5_switch_inputs E15
#define PIN_J1_5_event_inputs E15
#define PIN_J1_6_switch_inputs A6
#define PIN_J1_6_event_inputs A6
#define PIN_J1_7 MM100_OUT_PWM1
#define PIN_J1_8 MM100_INJ7
#define PIN_J1_9 MM100_IGN3
#define PIN_J1_17 MM100_IGN4
#define PIN_J1_22 MM100_IN_O2S_ANALOG
#define PIN_J1_23_switch_inputs E11
#define PIN_J1_23_event_inputs E11
#define PIN_J1_24 MM100_IN_IAT_ANALOG
#define PIN_J1_25 MM100_IGN5
#define PIN_J1_29 MM100_IN_AUX2_ANALOG
#define PIN_J1_30 MM100_IN_AUX1_ANALOG
#define PIN_J1_31 MM100_IN_MAP1_ANALOG
#define PIN_J1_32 MM100_IN_TPS_ANALOG
#define PIN_J1_33 MM100_IN_PPS_ANALOG
